version: "{build}"

cache:
  - '%AppData%\npm-cache'

build: off

platform:
  - x64
  - x86

environment:
  matrix:
    - nodejs_version: lts/boron
    - nodejs_version: lts/carbon
    - nodejs_version: current

install:
  - ps: Install-Product node $env:nodejs_version $env:platform
  - npm install

test_script:
  - node --version
  - npm --version
  - npm test
